### ISSUE TITLE
Several issues (including CLI injections)

### ISSUE THREAD

**Issue by iGEL** [jkraemer/pdf-forms#31]
Hi!

I've looked into this gem and have several issues with it.

1)
```ruby
  def test_fill_form_cli_injection
    @pdftk.fill_form 'test/fixtures/form.pdf', 'output.pdf"; touch "test/cli_injection', 'program_name' => 'SOME TEXT' rescue nil
    refute File.exist?('test/cli_injection'), "CLI injection successful"
  ensure
    FileUtils.rm 'output.pdf' if File.exist?('output.pdf')
    FileUtils.rm 'test/cli_injection' if File.exist?('test/cli_injection')
  end
```
This test fails (so I injected something in the CLI successfully), and I'm sure there are more examples of this. Don't use `%x #{command} #{args.join ' '} `, use `system(command, *args)`

2) Don't rescue `Exception`. You can rescue things that should fail, even syntax errors in included files. Rescue `StandardError` (which is the default) or a specific subclass.

3) `protected` has a different meaning in Ruby compared to most other languages, I think you want to use `private` everywhere. Not a real problem, though.

4) The gemspec is encoded with UTF-8, but the comment says ISO-8895-1. Causes rubygems.org to display your name with funny symbols.

**Comment by jkraemer** [comment]
Thanks for reporting this. I added your test and switched excution to SafeShell which internally uses `exec()`.

Regarding `rescue Exception` - I think that's fine because it a) its scope is very narrow and b) a `PdftkError` is always raised in this code path anyway, and it will include the original exception's message.
