### ISSUE TITLE
Support foreign characters.

### ISSUE THREAD

**Issue by kavitakanojiya** [jkraemer/pdf-forms#41]
Hey @jkraemer ,

I am trying to generate pdf with foreign characters. It works properly for french, portuguese, etc. But prints `????` for Arabic, Chinese and Hindi languages.

I upgraded this gem and now it points to 1.0.0 version. I used options as `encrypt: true, :encrypt_options => 'allow Printing'`, but nothing works.

Will you please provide any pointers to achieve this i.e to support all languages ?

Thanks

**Comment by jkraemer** [comment]
Try to use `:data_format => 'XFdf'` when initializing PdfForms / the PdftkWrapper. This will trigger use of the xfdf data format, which is supposed to work better with non-western languages.

Afair this is already mentioned in the README, but if you have success and want to improve documentation in this regard that would be great.

**Comment by sunil-sharma** [comment]
@jkraemer it didn't work.

**Comment by jkraemer** [comment]
Then I have a few questions:

- Are you sure the fonts used in the PDF you try to fill out actually contain the letters you want to show up? Sometimes Fonts are embedded in a document and they only contain those letters that are actually used in the document (that's an optimization to reduce file size).
- Does filling out and saving the form as a new PDF with Acrobat Reader give the result you want? If yes, can you run `pdftk the_filled_form.pdf dump_data_fields_utf8` and post it's output?

**Comment by ikusuki** [comment]
Hello,

Same thing happen to me with Japenese. This is the output of the previous command for the relevant field:
```
FieldType: Text
FieldName: nationality
FieldFlags: 0
FieldValue: スペイン
FieldJustification: Left
```

**Comment by ikusuki** [comment]
Just in case, this is the code I have (Rails) :

```
pdftk = PdfForms.new(utf8_fields: true, data_format: "XFdf")
    pdf_form = "#{Rails.root}/pdf/dan_registration.pdf"
    generated_pdf_form = "#{Rails.root}/pdf/dan_registration-#{Time.now.to_i}.pdf"
    fields = pdftk.get_field_names(pdf_form)
    field_hash = {}
    fields_filled = fields.each{|f| field_hash[f.to_sym] = params[f]}
    pdftk.fill_form pdf_form, generated_pdf_form, field_hash
   send_file(generated_pdf_form,
      disposition: "inline",
      type: "application/pdf",
      x_sendfile: true)
```

**Comment by jkraemer** [comment]
could you please send me the offending PDF form so I can have a look myself?

**Comment by jkraemer** [comment]
filling the nationality field with the value 'スペイン' worked fine for me - dump_data_fields_utf8 returned the same value for the form filled out via pdf-forms. I also just added a test case checking this, I hope it is ok that I used your form for this. Please object if otherwise. 

There seems to be an issue with the form however since I had to click into the form where I expected the 'nationality' field to be in order to get the value displayed. But this should be fixable in Adobe Acrobat by modifying field / document options.

**Comment by kavitakanojiya** [comment]
@jkraemer , hope you are doing fine. I debugged into this a bit. But no luck to me on this. It would be good if you could spare some time and have one-to-one discussion just to shed some light. Let me know if that is possible.

**Comment by jkraemer** [comment]
Have a look at [this PDF](http://www.pdfill.com/example/international_support_new.pdf). This has form values filled in a lot of different languages. Using the `pdffonts` tool you can see what fonts are used:

~~~~                           
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
TimesNewRomanPS-BoldMT               TrueType          WinAnsi          no  no  no      22  0
TimesNewRomanPSMT                    TrueType          WinAnsi          no  no  no      21  0
SKAGTA+ArialUnicodeMS                CID TrueType      Identity-H       yes yes yes      8  0
ArialUnicodeMS                       TrueType          WinAnsi          no  no  no       2  0
~~~~

So clearly it is possible, but it is entirely a problem of creating your form in the first place, nothing that can later be solved with `pdftk`.

My advice is to use a recent version of Adobe Acrobat when creating the form, and to embed fonts that support your desired target languages. For starters, the [ArialUnicodeMS](https://www.microsoft.com/typography/fonts/font.aspx?fmid=1081) appears to be a good choice. Be sure that font is used for the form fields (this should be a property somewhere in Acrobat), and be sure to turn font subsetting off.

If necessary (because you probably can not find a font supporting *all* languages of the world), create multiple versions of the form until you cover all desired languages.
