### ISSUE TITLE
Accented letters

### ISSUE THREAD

**Issue by porelli** [jkraemer/pdf-forms#57]
When I try to fill forms using some accented letters (à,ò, ecc...) these are missing from the PDF.

Rails 5.0.0.1
Ruby 2.3.1
pdf-forms 1.1.1

pdftk 2.02

pdf 1.6 generated with Acrobat DC

**Comment by jkraemer** [comment]
Usually this is just a font problem (embedded fonts in your PDF form do not contain those characters). Please run `pdftk your_filled_out.pdf dump_data_fields_utf8` and check the `FieldValue` of the fields where you think characters are missing.

If they show up here, it's a problem with your PDF document since PDFTK filled in the value correctly. If they aren't there in the dump_data_fields_output, please re-open this issue and post a form and code snippet for me to reproduce.
